spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_example?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: hzm.1437
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
